name: thingsboard

services:
  postgres:
    container_name: postgres
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./volumes/data/db:/var/lib/postgresql/data
      
  thingsboard-ce:
    container_name: thingsboard-ce
    restart: always
    image: "thingsboard/tb-node:4.1.0"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1883:1883"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-ce-node
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
    volumes:
      - ./volumes/logs:/var/log/thingsboard
    depends_on:
      - postgres

# volumes:
#   postgres-data:
#     name: tb-postgres-data
#     driver: local
